import json
import inspect
import time
import os
from google import genai
from dotenv import load_dotenv
from google.genai import types

load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

GEMINI_MODEL = "gemini-3.1-flash-lite"

def cleanTranscript(rawTranscript, videoTitle, videoTags, channel=""):
    rawTranscriptStr = json.dumps(rawTranscript, ensure_ascii=False)

    system_instruction = (
        "You are an expert transcript editor and JSON data specialist. "
        "Your sole job is to correct errors in speech-to-text output while preserving the original JSON structure exactly."
    )

    prompt = inspect.cleandoc(f"""
        You are given a raw JSON transcript generated by a speech-to-text model.
        Your task is to fix transcription errors using the video context provided below.

        ## Video Context
        - **Title:**   {videoTitle or "N/A"}
        - **Channel:** {channel or "N/A"}
        - **Tags:**    {videoTags or "N/A"}

        ## Raw Transcript (JSON)
        {rawTranscriptStr}

        ## Correction Rules (STRICTLY FOLLOW ALL)
        1. **Fix phonetic/homophone errors** caused by fast speech, regional accents, or similar-sounding syllables.
        2. **Normalize proper nouns** using the title, channel name, and tags as ground truth.
           - Example: If tags contain "Animal Crossing" and the transcript says "동물에서" → correct to "동물의 숲".
        3. **Do NOT paraphrase or rephrase** any sentence. Only fix clear transcription errors.
        4. **Do NOT change, add, or remove** any "time" field values. Timestamps are sacred.
        5. **Only modify** the "text" field values. Leave everything else identical.
        6. **Output must be valid JSON** with the exact same array structure as the input.

        Return only the corrected JSON array.""")

    config = types.GenerateContentConfig(
        system_instruction=system_instruction,
        response_mime_type="application/json",
        temperature=0.2
    )

    for attempt in range(1, 4):
        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=config
            )
            if response and response.text:
                return json.loads(response.text)
        except Exception as e:
            err_str = str(e)
            if "429" in err_str or "RESOURCE_EXHAUSTED" in err_str or "quota" in err_str.lower():
                wait_time = attempt * 3.0
                print(f"[llmEditor] {GEMINI_MODEL} bị 429 Quota (attempt {attempt}/3). Chờ {wait_time}s rồi thử lại...")
                time.sleep(wait_time)
            else:
                print(f"[llmEditor] Lỗi {GEMINI_MODEL}: {e}")
                time.sleep(1.5)

    return rawTranscript
