
import json
import os
from google import genai
from dotenv import load_dotenv
from google.genai import types

load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

def cleanTranscript(rawTranscript, videoTitle, videoTags):
    rawTranscriptStr = json.dumps(rawTranscript, ensure_ascii=False)

    system_instruction = (
        "You are an expert transcript editor and JSON data specialist. "
        "Your sole job is to correct errors in speech-to-text output while preserving the original JSON structure exactly."
    )

    prompt = f"""You are given a raw JSON transcript generated by a speech-to-text model. Your task is to fix transcription errors using the video context provided below.

    ## Video Context
    - **Title:** {videoTitle or "N/A"}
    - **Tags:** {videoTags or "N/A"}

    ## Raw Transcript (JSON)
    {rawTranscriptStr}

    ## Correction Rules (STRICTLY FOLLOW ALL)
    1. **Fix phonetic/homophone errors** caused by fast speech, regional accents, or similar-sounding syllables.
    - Example: "bah-kwee-bul-lee" → correct to the proper spelling based on context.
    2. **Normalize proper nouns** using the title and tags as ground truth.
    - Example: If tags contain "Animal Crossing" and the transcript says "동물에서" → correct to "동물의 숲".
    - Example: If a character name appears garbled → restore it using the tags.
    3. **Do NOT paraphrase or rephrase** any sentence. Only fix clear transcription errors.
    4. **Do NOT change, add, or remove** any "time" field values. Timestamps are sacred.
    5. **Only modify** the "text" field values. Leave everything else identical.
    6. **Output must be valid JSON** with the exact same array structure as the input — no extra keys, no commentary, no markdown fences.

    Return only the corrected JSON array."""

    try:
        response = client.models.generate_content(
            model="gemini-3.1-flash-lite",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type = "application/json"
            )
        )

        return json.loads(response.text)
    except Exception as e:
        print(f"Lỗi xử lý {e}")
        return rawTranscript  # Trả về list gốc thay vì string