import json
import gc
import inspect
import time
import torch
import ollama
import os
from google import genai
from dotenv import load_dotenv
from google.genai import types

load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

GEMINI_MODEL = "gemini-3.1-flash-lite"

def cleanTranscript(rawTranscript, videoTitle, videoTags, channel=""):
    rawTranscriptStr = json.dumps(rawTranscript, ensure_ascii=False)

    system_instruction = (
        "You are an expert transcript editor and JSON data specialist. "
        "Your sole job is to correct errors in speech-to-text output while preserving the original JSON structure exactly."
    )

    prompt = inspect.cleandoc(f"""
        You are given a raw JSON transcript generated by a speech-to-text model.
        Your task is to fix transcription errors using the video context provided below.

        ## Video Context
        - **Title:**   {videoTitle or "N/A"}
        - **Channel:** {channel or "N/A"}
        - **Tags:**    {videoTags or "N/A"}

        ## Raw Transcript (JSON)
        {rawTranscriptStr}

        ## Correction Rules (STRICTLY FOLLOW ALL)
        1. **Fix phonetic/homophone errors** caused by fast speech, regional accents, or similar-sounding syllables.
        2. **Normalize proper nouns** using the title, channel name, and tags as ground truth.
           - Example: If tags contain "Animal Crossing" and the transcript says "동물에서" → correct to "동물의 숲".
        3. **Do NOT paraphrase or rephrase** any sentence. Only fix clear transcription errors.
        4. **Do NOT change, add, or remove** any "time" field values. Timestamps are sacred.
        5. **Only modify** the "text" field values. Leave everything else identical.
        6. **Output must be valid JSON** with the exact same array structure as the input.

        Return only the corrected JSON array.""")

    config = types.GenerateContentConfig(
        system_instruction=system_instruction,
        response_mime_type="application/json",
        temperature=0.2
    )

    for attempt in range(1, 4):
        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=config
            )
            if response and response.text:
                return json.loads(response.text)
        except Exception as e:
            err_str = str(e)
            if "429" in err_str or "RESOURCE_EXHAUSTED" in err_str or "quota" in err_str.lower():
                wait_time = attempt * 3.0
                print(f"[llmEditor] {GEMINI_MODEL} bị 429 Quota (attempt {attempt}/3). Chờ {wait_time}s rồi thử lại...")
                time.sleep(wait_time)
            else:
                print(f"[llmEditor] Lỗi {GEMINI_MODEL}: {e}")
                time.sleep(1.5)

    return rawTranscript


LANG_NAME_MAP = {
    "vi": "Vietnamese",
    "en": "English",
    "ja": "Japanese",
    "ko": "Korean",
    "zh": "Chinese (Simplified)",
    "fr": "French",
    "de": "German",
    "es": "Spanish",
    "th": "Thai",
    "id": "Indonesian",
    "ru": "Russian",
    "pt": "Portuguese",
    "it": "Italian",
    "ar": "Arabic",
}


def clear_vram():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print("[VRAM] Cleared GPU memory.")


def _extract_segments(raw):
    if isinstance(raw, list):
        return raw
    if isinstance(raw, dict):
        if "segments" in raw and isinstance(raw["segments"], list):
            return raw["segments"]
        for v in raw.values():
            if isinstance(v, list):
                return v
        values = list(raw.values())
        if values and all(isinstance(v, dict) for v in values):
            return values
        for v in values:
            if isinstance(v, dict):
                result = _extract_segments(v)
                if result is not None:
                    return result
    return None

def translate_subtitles(data, src_lang="en", tgt_lang="vi", batch_size=10):
    src_lang_name = LANG_NAME_MAP.get(src_lang, src_lang)
    tgt_lang_name = LANG_NAME_MAP.get(tgt_lang, tgt_lang)
    final_output = []
    total_batches = (len(data) + batch_size - 1) // batch_size

    system_prompt = (
        f"You are a professional subtitle translator specializing in {src_lang_name} to {tgt_lang_name} translation. "
        "You receive subtitle segments and return a JSON object with a 'segments' key "
        "containing the translated array. "
        "You NEVER output a bare JSON array — always wrap in {\"segments\": [...]}. "
        "You ONLY output raw valid JSON."
    )

    few_shot = inspect.cleandoc(f"""
        ### Example
        Input:
        [
          {{"time": "00:00:05", "text": "Welcome back to the channel!"}},
          {{"time": "00:00:08", "text": "Today we're reviewing the latest iPhone."}}
        ]

        Output ({src_lang_name} → {tgt_lang_name}):
        {{
          "segments": [
            {{"time": "00:00:05", "text": "Welcome back to the channel!", "translated": "Chào mừng bạn quay lại kênh!"}},
            {{"time": "00:00:08", "text": "Today we're reviewing the latest iPhone.", "translated": "Hôm nay chúng ta sẽ review chiếc iPhone mới nhất."}}
          ]
        }}""")

    for i in range(0, len(data), batch_size):
        batch = data[i: i + batch_size]
        batch_str = json.dumps(batch, ensure_ascii=False, indent=2)
        current_batch = i // batch_size + 1
        print(f"[LLM Translate] Batch {current_batch}/{total_batches}...")

        user_prompt = inspect.cleandoc(f"""
            ## Task
            Translate ALL {len(batch)} subtitle segments from {src_lang_name} into {tgt_lang_name}.
            Add a "translated" field to each item. All other fields must remain exactly as in the input.

            ## Required Output Format
            Return a JSON object with key "segments" containing ALL {len(batch)} translated items:
            {{
              "segments": [
                {{"time": <string UNCHANGED>, "text": <string UNCHANGED>, "translated": <{tgt_lang_name} string>}},
                ... (one entry per input item)
              ]
            }}

            ## Rules
            - Output MUST contain exactly {len(batch)} items in "segments".
            - Translate naturally and fluently — prioritize meaning over literal word-for-word.
            - Do NOT translate proper nouns, brand names, or technical terms commonly used as-is.
            - Keep "time" and "text" values EXACTLY as in the input.

            {few_shot}

            ## Input ({len(batch)} segments)
            {batch_str}""")

        MAX_RETRIES = 3
        ctx_per_attempt = [4096, 6144, 8192]
        success = False

        for attempt in range(1, MAX_RETRIES + 1):
            try:
                response = ollama.chat(
                    model='qwen3:8b',
                    messages=[
                        {'role': 'system', 'content': system_prompt},
                        {'role': 'user',   'content': user_prompt},
                    ],
                    format='json',
                    options={
                        'temperature': 0.2,
                        'top_p': 0.9,
                        'num_ctx': ctx_per_attempt[attempt - 1],
                    }
                )

                result = _extract_segments(json.loads(response.message.content))
                if result is not None:
                    merged = []
                    for j, orig in enumerate(batch):
                        if j < len(result):
                            translated_val = result[j].get("translated", "")
                            merged.append({
                                "time":       orig["time"],
                                "text":       orig["text"],
                                "translated": translated_val,
                            })
                        else:
                            merged.append(orig)
                    final_output.extend(merged)
                    success = True
                    break
                else:
                    raw_content = response.message.content
                    print(f"[LLM Translate] Warning: unexpected format in batch {current_batch} "
                          f"(attempt {attempt}). Raw: {raw_content[:200]}")

            except Exception as e:
                print(f"[LLM Translate Error] Batch {current_batch}/{total_batches} "
                      f"(attempt {attempt}/{MAX_RETRIES}): {e}")
                if attempt < MAX_RETRIES:
                    print(f"[LLM Translate] Retrying with num_ctx={ctx_per_attempt[attempt]}...")

        if not success:
            print(f"[LLM Translate] Batch {current_batch} failed after {MAX_RETRIES} attempts. Skipping.")
            final_output.extend(batch)

    return final_output
